version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: documind-postgres-db
    restart: always
    environment:
      POSTGRES_USER: neondb_owner
      POSTGRES_PASSWORD: npg_DMUI0BPw5FJR
      POSTGRES_DB: neondb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: documind-fastapi-backend
    restart: always
    environment:
      - DATABASE_URL=postgresql://neondb_owner:npg_DMUI0BPw5FJR@db:5432/neondb
      - GOOGLE_CLIENT_ID=1034948744999-0a29fr7khu9e08luec1mbrng63uslq60.apps.googleusercontent.com
      - JWT_SECRET=rag-for-docs-super-secret-key-change-this-in-production
      - GROQ_API_KEY=your_groq_api_key_here
      - PORT=8000
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./backend/chroma_db:/home/user/app/chroma_db

volumes:
  pgdata:
